//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int Id { get; set; }
        public int PetId { get; set; }
        public int VisitId { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
